version: '3.7'

services:
  api:
    build: 
      context: ./modules/api
    depends_on:
      - db
      - persons
      - locations
    networks:
      - default
    environment:
      - PERSON_SERVICE_URL=http://persons:5000
      - LOCATION_SERVICE_ADDR=locations:5005
      - FLASK_ENV=dev
    restart: unless-stopped
    expose:
      - "5000"
    ports:
      - "127.0.0.1:5000:5000"
  persons:
    build: 
      context: ./modules/persons
    depends_on:
      - db
    networks:
      - default
    environment:
      - DB_USERNAME=udaconnect
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=udaconnect
    restart: unless-stopped
    expose:
      - "5000"
    ports:
      - "127.0.0.1:5001:5000"
  locations:
    build: 
      context: ./modules/locations
    depends_on:
      - db
      - kafka
    networks:
      - default
    environment:
      - DB_USERNAME=udaconnect
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=udaconnect
      - KAFKA_TOPIC=locations
      - KAFKA_ADDR=kafka:9092
    restart: unless-stopped
    expose:
      - "5005"
    ports:
      - "127.0.0.1:5005:5005"
  locationwriter:
    build: 
      context: ./modules/locationwriter
    depends_on:
      - db
      - kafka
    networks:
      - default
    environment:
      - DB_USERNAME=udaconnect
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=udaconnect
      - KAFKA_TOPIC=locations
      - KAFKA_ADDR=kafka:9092
    restart: unless-stopped
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    expose:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - default
  kafka:
    image: 'bitnami/kafka:latest'
    expose:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - default
  db:
    image: postgis/postgis:12-2.5-alpine
    environment:
      - POSTGRES_USER=udaconnect
      - POSTGRES_DB=udaconnect
      - POSTGRES_PASSWORD=secret
    expose:
      - "5432"
    volumes:
      - postgres_data_udaconnect:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default
    restart: unless-stopped


networks:
  default:

volumes:
  postgres_data_udaconnect:

