version: '3.7'

services:
  api:
    build: 
      context: ./modules/api
    depends_on:
      - db
      - persons
      - locations
    networks:
      - default
    environment:
      - PERSON_SERVICE_URL=http://persons:5000
      - LOCATION_SERVICE_ADDR=locations:5005
      - FLASK_ENV=dev
    restart: unless-stopped
    expose:
      - "5000"
    ports:
      - "127.0.0.1:5000:5000"
  persons:
    build: 
      context: ./modules/persons
    depends_on:
      - db
    networks:
      - default
    environment:
      - DB_USERNAME=udaconnect
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=udaconnect
    restart: unless-stopped
    expose:
      - "5000"
    ports:
      - "127.0.0.1:5001:5000"
  locations:
    build: 
      context: ./modules/locations
    depends_on:
      - db
    networks:
      - default
    environment:
      - DB_USERNAME=udaconnect
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=udaconnect
    restart: unless-stopped
    expose:
      - "5005"
    ports:
      - "127.0.0.1:5005:5005"
  db:
    image: postgis/postgis:12-2.5-alpine
    environment:
      - POSTGRES_USER=udaconnect
      - POSTGRES_DB=udaconnect
      - POSTGRES_PASSWORD=secret
    expose:
      - "5432"
    volumes:
      - postgres_data_udaconnect:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default
    restart: unless-stopped


networks:
  default:

volumes:
  postgres_data_udaconnect:

