apiVersion: v1
kind: ConfigMap
data:
  PERSON_SERVICE_URL: http://udaconnect-persons:5000
  LOCATION_SERVICE_ADDR: udaconnect-locations:5005
  KAFKA_ADDR: kafka-release:9092
  KAFKA_TOPIC: locations
metadata:
  name: app-env
