apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations
  name: udaconnect-locations
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    #nodePort: 30002
  selector:
    service: udaconnect-locations
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations
  name: udaconnect-locations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations
  template:
    metadata:
      labels:
        service: udaconnect-locations
    spec:
      containers:
      - image: gosom/nd064-udaconnect-locations:latest
        name: udaconnect-locations
        imagePullPolicy: Always
        env:
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-env
              key: KAFKA_TOPIC
        - name: KAFKA_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-env
              key: KAFKA_ADDR
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
